In [1]:
import pandas as pd

# App data
app_data = {
  'app_name': [
    'YouTube', 'TikTok', 'Instagram', 'Spotify', 'Duolingo', 
    'Twitter', 'Headspace', 'Discord', 'Depop'
  ],
  'category': [
    'Video', 'Social Media', 'Social Media', 'Music', 'Education',
    'Social Media', 'Health', 'Communication', 'Shopping'
  ],
  'rating': [
    4.7, 4.6, 4.5, 4.6, 4.7,
    4.3, None, 4.7, 4.4
  ],
  'downloads_millions': [
    5000, 3000, 3500, 2000, None,
    1500, 500, 600, 200
  ]
}

# Create the DataFrame
apps = pd.DataFrame(app_data)
apps

    app_name       category  rating  downloads_millions
0    YouTube          Video     4.7              5000.0
1     TikTok   Social Media     4.6              3000.0
2  Instagram   Social Media     4.5              3500.0
3    Spotify          Music     4.6              2000.0
4   Duolingo      Education     4.7                 NaN
5    Twitter   Social Media     4.3              1500.0
6  Headspace         Health     NaN               500.0
7    Discord  Communication     4.7               600.0
8      Depop       Shopping     4.4               200.0

In [2]:
#adding a column named downloaded that contains true/false based on whether i have app downloaded on my phone:
apps['downloaded'] = [True, True, True, True, True, False, False, True, False]
apps

    app_name       category  rating  downloads_millions  downloaded
0    YouTube          Video     4.7              5000.0        True
1     TikTok   Social Media     4.6              3000.0        True
2  Instagram   Social Media     4.5              3500.0        True
3    Spotify          Music     4.6              2000.0        True
4   Duolingo      Education     4.7                 NaN        True
5    Twitter   Social Media     4.3              1500.0       False
6  Headspace         Health     NaN               500.0       False
7    Discord  Communication     4.7               600.0        True
8      Depop       Shopping     4.4               200.0       False

In [3]:
# sort the apps by rating so highest rated apps are at the top of the dataframe:
apps.sort_values(by='rating', ascending=False)
apps

    app_name       category  rating  downloads_millions  downloaded
0    YouTube          Video     4.7              5000.0        True
1     TikTok   Social Media     4.6              3000.0        True
2  Instagram   Social Media     4.5              3500.0        True
3    Spotify          Music     4.6              2000.0        True
4   Duolingo      Education     4.7                 NaN        True
5    Twitter   Social Media     4.3              1500.0       False
6  Headspace         Health     NaN               500.0       False
7    Discord  Communication     4.7               600.0        True
8      Depop       Shopping     4.4               200.0       False

In [4]:
# rename column of app_name to name:
apps = apps.rename(columns={'app_name':'name'})
apps

        name       category  rating  downloads_millions  downloaded
0    YouTube          Video     4.7              5000.0        True
1     TikTok   Social Media     4.6              3000.0        True
2  Instagram   Social Media     4.5              3500.0        True
3    Spotify          Music     4.6              2000.0        True
4   Duolingo      Education     4.7                 NaN        True
5    Twitter   Social Media     4.3              1500.0       False
6  Headspace         Health     NaN               500.0       False
7    Discord  Communication     4.7               600.0        True
8      Depop       Shopping     4.4               200.0       False