In [1]:
import pandas as pd

# D&D characters data
characters_data = {
  'name': ['Thorne', 'Elira', 'Glim', 'Brug', 'Nyx', 'Kael', 'Mira', 'Drogan', 'Zara', 'Fenwick'],
  'race': ['Elf', 'Human', 'Gnome', 'Half-Orc', 'Tiefling', 'Dragonborn', 'Halfling', 'Dwarf', 'Aasimar', 'Goblin'],
  'class': ['Ranger', 'Cleric', 'Wizard', 'Barbarian', 'Rogue', 'Paladin', 'Bard', 'Fighter', 'Sorcerer', 'Warlock'],
  'level': [5, 3, 4, 2, 6, 7, 3, 5, 4, 2],
  'hp': [42, 28, 33, 25, 48, 56, 30, 44, 36, 24],
  'alignment': [
    'Chaotic Good', 'Lawful Good', 'Neutral', 'Chaotic Neutral', 'Chaotic Evil',
    'Lawful Neutral', 'Neutral Good', 'Neutral', 'Chaotic Good', 'Lawful Evil'
  ]
}

# Create the DataFrame
characters = pd.DataFrame(characters_data)
characters

      name        race      class  level  hp        alignment
0   Thorne         Elf     Ranger      5  42     Chaotic Good
1    Elira       Human     Cleric      3  28      Lawful Good
2     Glim       Gnome     Wizard      4  33          Neutral
3     Brug    Half-Orc  Barbarian      2  25  Chaotic Neutral
4      Nyx    Tiefling      Rogue      6  48     Chaotic Evil
5     Kael  Dragonborn    Paladin      7  56   Lawful Neutral
6     Mira    Halfling       Bard      3  30     Neutral Good
7   Drogan       Dwarf    Fighter      5  44          Neutral
8     Zara     Aasimar   Sorcerer      4  36     Chaotic Good
9  Fenwick      Goblin    Warlock      2  24      Lawful Evil

In [2]:
# create df for all characters above level 5:
above_five = characters[characters['level']>5]
above_five

   name        race    class  level  hp       alignment
4   Nyx    Tiefling    Rogue      6  48    Chaotic Evil
5  Kael  Dragonborn  Paladin      7  56  Lawful Neutral

In [3]:
# create df for all characters whose race is Halfling and class is Bard:
halfling_bards = characters[
    (characters['race'] == 'Halfling') & (characters['class'] == 'Bard')
]
halfling_bards

   name      race class  level  hp     alignment
6  Mira  Halfling  Bard      3  30  Neutral Good

In [4]:
# create df whose character is either Wizard, Sorcerer or Warlock
magic_users = characters[
    (characters['class'] == 'Wizard') |(characters['class'] == 'Sorcer') |(characters['class'] == 'Warlock') 
]

magic_users

      name    race    class  level  hp    alignment
2     Glim   Gnome   Wizard      4  33      Neutral
9  Fenwick  Goblin  Warlock      2  24  Lawful Evil