In [1]:
import pandas as pd

data = {
    'character_names': ['Robert Nash', 'Evan Buckley', 'Eddie Diaz', 'Henrietta Wilson', 'Howard Han', 'Christopher Diaz', 'Maddie Buckley Han', 'Athena Grant'],
    'nicknames': ['Bobby', 'Buck', 'Eddie', 'Hen', 'Chimney', 'Chris', 'Maddie', 'Thena'],
    'job':['Captain (former)', 'Firefighter', 'Firefighter', 'Paramedic', 'Captain', 'Student', 'Dispatcher', 'Police Sergent'],
    'age': [56, 39, 38, 42, 46, 14, 36, 51],
    'relationship': [True, True, True, True, True, False, True, True]
}

characters = pd.DataFrame(data)
characters

      character_names nicknames               job  age  relationship
0         Robert Nash     Bobby  Captain (former)   56          True
1        Evan Buckley      Buck       Firefighter   39          True
2          Eddie Diaz     Eddie       Firefighter   38          True
3    Henrietta Wilson       Hen         Paramedic   42          True
4          Howard Han   Chimney           Captain   46          True
5    Christopher Diaz     Chris           Student   14         False
6  Maddie Buckley Han    Maddie        Dispatcher   36          True
7        Athena Grant     Thena    Police Sergent   51          True

In [2]:
# add a column for who they are in relationship with:
characters['partner'] = ['Athena Grant', 'Eddie Diaz', 'Evan Buckley', 'Karen', 'Maddie Buckley Han', 'None', 'Howard Han', 'Robert Nash']
characters

,character_names,nicknames,job,age,relationship,partner
0,Robert Nash,Bobby,Captain (former),56,True,Athena Grant
1,Evan Buckley,Buck,Firefighter,39,True,Eddie Diaz
2,Eddie Diaz,Eddie,Firefighter,38,True,Evan Buckley
3,Henrietta Wilson,Hen,Paramedic,42,True,Karen
4,Howard Han,Chimney,Captain,46,True,Maddie Buckley Han
5,Christopher Diaz,Chris,Student,14,False,None
6,Maddie Buckley Han,Maddie,Dispatcher,36,True,Howard Han
7,Athena Grant,Thena,Police Sergent,51,True,Robert Nash

In [7]:
# sort data frame by stat- i'll do age :D
characters_sorted = characters.sort_values(by='age', ascending=False)
characters_sorted

,character_names,nicknames,job,age,relationship,partner
0,Robert Nash,Bobby,Captain (former),56,True,Athena Grant
7,Athena Grant,Thena,Police Sergent,51,True,Robert Nash
4,Howard Han,Chimney,Captain,46,True,Maddie Buckley Han
3,Henrietta Wilson,Hen,Paramedic,42,True,Karen
1,Evan Buckley,Buck,Firefighter,39,True,Eddie Diaz
2,Eddie Diaz,Eddie,Firefighter,38,True,Evan Buckley
6,Maddie Buckley Han,Maddie,Dispatcher,36,True,Howard Han
5,Christopher Diaz,Chris,Student,14,False,None

In [8]:
# get paramedics only:
paramedics = characters[characters['job']=='Paramedic']
paramedics

    character_names nicknames        job  age  relationship partner
3  Henrietta Wilson       Hen  Paramedic   42          True   Karen

In [9]:
# over forty:
over_forty = characters[characters['age']>=40]
over_forty

,character_names,nicknames,job,age,relationship,partner
0,Robert Nash,Bobby,Captain (former),56,True,Athena Grant
3,Henrietta Wilson,Hen,Paramedic,42,True,Karen
4,Howard Han,Chimney,Captain,46,True,Maddie Buckley Han
7,Athena Grant,Thena,Police Sergent,51,True,Robert Nash